/*jshint esversion: 6 */
var https = require('https');
var express = require("express");
var bodyParser = require("body-parser");
var session = require("express-session");

var databoxRequest = require('./lib/databox-request.js');
var databoxDatasourceHelper = require('./lib/databox-datasource-helper.js');

//The endpoint for my datastore (Where i can publish my sentiment data)
const DATABOX_STORE_BLOB_ENDPOINT = process.env.DATABOX_APP_TWITTER_SENTIMENT_DATABOX_STORE_BLOB_ENDPOINT || '';

//The endpoint for the datasource requested in the manifest ( env var name derived from the id in the manifest)
const USER_TIMELINE_ENDPOINT = process.env.DATASOURCE_userTimeLine || '';

//My https cred generated by the container manager
var HTTPS_CLIENT_CERT = process.env.HTTPS_CLIENT_CERT || '';
var HTTPS_CLIENT_PRIVATE_KEY = process.env.HTTPS_CLIENT_PRIVATE_KEY || '';
var credentials = {
	key:  HTTPS_CLIENT_PRIVATE_KEY,
	cert: HTTPS_CLIENT_CERT,
};

var app = express();

var status = "init";
app.get("/status", function(req, res) {
    res.send(status);
});

//start the express server
https.createServer(credentials, app).listen(8080);

//
// wait for our datastores to be ready
//
status = "Wait for datastore";
databoxDatasourceHelper.waitForDatastore(DATABOX_STORE_BLOB_ENDPOINT)
  .then(() =>{
      
      return databoxDatasourceHelper.waitForDatastore();
      
  })
  .then(() =>{
      status = "active";

      //Register my sentiment datasource with my store to make it available to other apps
      proms = [
        databoxDatasourceHelper.registerDatasource(DATABOX_STORE_BLOB_ENDPOINT, 'databox-app-twitter-sentiment', 'twitterUserTimeLineSentiment','twitterUserTimeLineSentiment', '', 'Twitter user timeline Sentiment', ''),
      ];
    return Promise.all(proms);

  })
  .then(()=>{
      //register for live streaming data from the databox-driver-twitter-stream
      subscribeToDatasource(USER_TIMELINE_ENDPOINT, function (data) {
          //New data has been written into the store
          console.log("NEW DATA::",data);
          //update our sentiment analysis

      });
  })
  .catch((error)=>{
      status="error";
      console.log(error);
  });

module.exports = app;